import { StudyModule } from "@/types/youtube";

export const STUDY_MODULES: StudyModule[] = [
  {
    id: "module-1-greetings",
    title: "Module 1: Essential ISL Greetings & Courtesies",
    subtitle: "Learn fundamental polite interactions in Indian Sign Language",
    description: "Discover how to greet friends, say Namaste, express gratitude, and introduce yourself using standard Indian Sign Language hand configurations.",
    category: "GREETINGS",
    difficulty: "BEGINNER",
    videoId: "mD1T8U3_cT8", // Example high quality ISL tutorial video
    videoTitle: "Indian Sign Language Basics: Daily Greetings & Etiquette",
    videoDuration: "03:45",
    thumbnailUrl: "https://img.youtube.com/vi/mD1T8U3_cT8/hqdefault.jpg",
    curatedSignIds: ["HELLO", "THANK YOU", "YES", "NO"],
    fallbackCues: [
      {
        id: "cue-1",
        start: 0.0,
        duration: 4.5,
        end: 4.5,
        text: "Welcome to Indian Sign Language fundamentals. Today we learn essential daily greetings.",
      },
      {
        id: "cue-2",
        start: 4.5,
        duration: 5.2,
        end: 9.7,
        text: "First greeting is Hello or Namaste. Bring your palms together near chest level with gentle nod.",
      },
      {
        id: "cue-3",
        start: 9.7,
        duration: 6.0,
        end: 15.7,
        text: "To wave Hello informally, raise dominant hand near temple and gently extend outward.",
      },
      {
        id: "cue-4",
        start: 15.7,
        duration: 6.8,
        end: 22.5,
        text: "Next is Thank You. Touch your chin with flat fingertips and sweep forward with open palm.",
      },
      {
        id: "cue-5",
        start: 22.5,
        duration: 5.5,
        end: 28.0,
        text: "For Yes, create a gentle closed fist and nod knuckles downward twice from your wrist.",
      },
      {
        id: "cue-6",
        start: 28.0,
        duration: 6.2,
        end: 34.2,
        text: "For No, snap index and middle finger against thumb, or wave flat palm side-to-side.",
      },
      {
        id: "cue-7",
        start: 34.2,
        duration: 5.8,
        end: 40.0,
        text: "Practice these signs repeatedly in front of your camera in Gesturify to test your form.",
      },
    ],
  },
  {
    id: "module-2-emergency",
    title: "Module 2: Urgent Assistance & Medical Signs",
    subtitle: "Vital emergency communication for first responders and safety",
    description: "Learn how to signal urgent distress, request a doctor or medicine, call for police help, and communicate pain or immediate needs.",
    category: "EMERGENCY",
    difficulty: "BEGINNER",
    videoId: "a9_i2m3tT3E",
    videoTitle: "ISL Emergency & Healthcare Communication Guide",
    videoDuration: "04:12",
    thumbnailUrl: "https://img.youtube.com/vi/a9_i2m3tT3E/hqdefault.jpg",
    curatedSignIds: ["HELP", "STOP"],
    fallbackCues: [
      {
        id: "cue-em-1",
        start: 0.0,
        duration: 4.0,
        end: 4.0,
        text: "Emergency signs are essential for rapid, life-saving communication in any critical situation.",
      },
      {
        id: "cue-em-2",
        start: 4.0,
        duration: 5.8,
        end: 9.8,
        text: "The universal sign for Help: place closed fist with thumb up onto flat non-dominant palm and lift upward.",
      },
      {
        id: "cue-em-3",
        start: 9.8,
        duration: 6.2,
        end: 16.0,
        text: "To signal Stop or Halt: chop flat vertical dominant hand sharply onto horizontal open palm.",
      },
      {
        id: "cue-em-4",
        start: 16.0,
        duration: 5.5,
        end: 21.5,
        text: "Always maintain clear facial expressions indicating urgency while demonstrating distress gestures.",
      },
      {
        id: "cue-em-5",
        start: 21.5,
        duration: 6.0,
        end: 27.5,
        text: "Use the Gesturify live vision scanner to verify your hand placement for emergency triggers.",
      },
    ],
  },
  {
    id: "module-3-essentials",
    title: "Module 3: Daily Conversation & Common Needs",
    subtitle: "Food, water, asking questions, and household expressions",
    description: "Expand your fluency with signs for water, eating food, asking questions, and understanding basic conversation flow.",
    category: "DAILY_LIFE",
    difficulty: "INTERMEDIATE",
    videoId: "u9PjX6Tq4zY",
    videoTitle: "Daily Life Phrases & Questions in Indian Sign Language",
    videoDuration: "05:20",
    thumbnailUrl: "https://img.youtube.com/vi/u9PjX6Tq4zY/hqdefault.jpg",
    curatedSignIds: ["WATER", "FOOD", "WHERE"],
    fallbackCues: [
      {
        id: "cue-dl-1",
        start: 0.0,
        duration: 4.2,
        end: 4.2,
        text: "In this module, we explore everyday essentials: food, drinking water, and asking questions.",
      },
      {
        id: "cue-dl-2",
        start: 4.2,
        duration: 5.6,
        end: 9.8,
        text: "To sign Water: form a 'W' handshape with three fingers near your chin and tap gently twice.",
      },
      {
        id: "cue-dl-3",
        start: 9.8,
        duration: 6.0,
        end: 15.8,
        text: "For Food or Eat: bring clustered fingertips toward your mouth mimicking taking a bite.",
      },
      {
        id: "cue-dl-4",
        start: 15.8,
        duration: 5.4,
        end: 21.2,
        text: "When asking Where, hold both palms facing upward and sway hands laterally with questioning eyes.",
      },
      {
        id: "cue-dl-5",
        start: 21.2,
        duration: 6.5,
        end: 27.7,
        text: "Combine these signs into full sentences like 'Where is water' or 'I need food now'.",
      },
    ],
  },
];
