export interface MatchedSignToken {
  id: string;
  label: string;
  hindiLabel: string;
  category: string;
}

export interface TranscriptCue {
  id: string;
  start: number;       // Start offset in seconds (e.g. 14.5)
  duration: number;    // Duration in seconds (e.g. 3.2)
  end: number;         // End offset in seconds (start + duration)
  text: string;        // Caption transcript text
  matchedSigns: MatchedSignToken[]; // Cross-referenced Gesturify ISL signs
}

export interface YouTubeCaptionTrack {
  baseUrl: string;
  name: string;
  languageCode: string;
  isAutoGenerated: boolean;
}

export interface YouTubeTranscriptResponse {
  success: boolean;
  videoId: string;
  videoTitle?: string;
  language?: string;
  availableLanguages?: { code: string; name: string; isAuto?: boolean }[];
  cues: TranscriptCue[];
  cached?: boolean;
  source?: "youtube-timedtext" | "curated-lesson" | "fallback";
  error?: string;
}

export interface StudyModule {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  category: "BASICS" | "GREETINGS" | "EMERGENCY" | "DAILY_LIFE" | "PRACTICE";
  difficulty: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
  videoId: string;
  videoTitle: string;
  videoDuration: string;
  thumbnailUrl: string;
  curatedSignIds: string[];
  fallbackCues?: Omit<TranscriptCue, "matchedSigns">[];
}
